CREATE PROCEDURE [dbo].[GetDatabaseRowVersion]
AS
BEGIN
    SET NOCOUNT ON;

    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    SELECT 
        DBTS = CONVERT(BIGINT, MIN_ACTIVE_ROWVERSION()) - 1;
END;
GO